package pojos;
// Generated 22-06-2019 3:49:21 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Artista generated by hbm2java
 */
@Entity
@Table(name="artista"
    ,catalog="disketo_ejercicio"
)
public class Artista  implements java.io.Serializable {


     private Integer idArtista;
     private Estado estado;
     private Genero genero;
     private String nombreArtista;
     private String origenArtista;
     private Integer formadoArtista;
     private String tematicaArtista;

    public Artista() {
    }

	
    public Artista(Estado estado, Genero genero, String nombreArtista) {
        this.estado = estado;
        this.genero = genero;
        this.nombreArtista = nombreArtista;
    }
    public Artista(Estado estado, Genero genero, String nombreArtista, String origenArtista, Integer formadoArtista, String tematicaArtista) {
       this.estado = estado;
       this.genero = genero;
       this.nombreArtista = nombreArtista;
       this.origenArtista = origenArtista;
       this.formadoArtista = formadoArtista;
       this.tematicaArtista = tematicaArtista;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idArtista", unique=true, nullable=false)
    public Integer getIdArtista() {
        return this.idArtista;
    }
    
    public void setIdArtista(Integer idArtista) {
        this.idArtista = idArtista;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEstado", nullable=false)
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idGenero", nullable=false)
    public Genero getGenero() {
        return this.genero;
    }
    
    public void setGenero(Genero genero) {
        this.genero = genero;
    }

    
    @Column(name="nombreArtista", nullable=false, length=50)
    public String getNombreArtista() {
        return this.nombreArtista;
    }
    
    public void setNombreArtista(String nombreArtista) {
        this.nombreArtista = nombreArtista;
    }

    
    @Column(name="origenArtista", length=50)
    public String getOrigenArtista() {
        return this.origenArtista;
    }
    
    public void setOrigenArtista(String origenArtista) {
        this.origenArtista = origenArtista;
    }

    
    @Column(name="formadoArtista")
    public Integer getFormadoArtista() {
        return this.formadoArtista;
    }
    
    public void setFormadoArtista(Integer formadoArtista) {
        this.formadoArtista = formadoArtista;
    }

    
    @Column(name="tematicaArtista", length=100)
    public String getTematicaArtista() {
        return this.tematicaArtista;
    }
    
    public void setTematicaArtista(String tematicaArtista) {
        this.tematicaArtista = tematicaArtista;
    }




}


