package model.pojo;
// Generated 03-06-2019 23:52:34 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;


/**
 * Genero generated by hbm2java
 */
@Entity
@Table(name = "genero",
         catalog = "disketo_ejercicio",
         uniqueConstraints = @UniqueConstraint(columnNames = "nombreGenero")
)
public class Genero implements java.io.Serializable {

    private Integer idGenero;
    private String nombreGenero;
    private Set artistas = new HashSet(0);

    public Genero() {
    }


    public Genero(String nombreGenero) {
        this.nombreGenero = nombreGenero;
    }


    public Genero(String nombreGenero, Set artistas) {
        this.nombreGenero = nombreGenero;
        this.artistas = artistas;
    }


    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idGenero", unique = true, nullable = false)
    public Integer getIdGenero() {
        return this.idGenero;
    }


    public void setIdGenero(Integer idGenero) {
        this.idGenero = idGenero;
    }


    @Column(name = "nombreGenero", unique = true, nullable = false, length = 50)
    public String getNombreGenero() {
        return this.nombreGenero;
    }


    public void setNombreGenero(String nombreGenero) {
        this.nombreGenero = nombreGenero;
    }


    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "genero")
    public Set getArtistas() {
        return this.artistas;
    }


    public void setArtistas(Set artistas) {
        this.artistas = artistas;
    }


}
